# This is a basic workflow to help you get started with Actions

name: API Test

# Controls when the workflow will run
on:
  # Triggers to run daily at 17:30 UTC
  schedule:
    - cron: '30 5,17 * * *'
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: macos-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Bootstrap SDK
        run: cmake -DIS_BUILD_AND_TEST=ON -P bootstrap.cmake

